Changes to use python-ipware
jrobichaud/django-structlog pull request #358
Opened 2023-10-25 14:51 UTC by rposborne

As django-ipware is being deprecated in favor of python-ipware, and the fact they share the same import namespace any project python-ipware

2023-10-25 14:57 UTC, jrobichaud requested changes
`pyproject.toml` needs to be modified.

2023-10-25 15:02 UTC, jrobichaud commented on django_structlog/middlewares/request.py
> +    ipw = IpWare()
I think it has to be added to `app_settings.py` and be configurable through settings.

2023-10-25 15:06 UTC, rposborne commented on django_structlog/middlewares/request.py
> +        meta = request.META
Neat was only reacting to the existing pattern here.

2023-10-25 15:07 UTC, jrobichaud commented on django_structlog/middlewares/request.py
> +        meta = request.META
MY BAD, we are still supporting 3.2. keep it.

2023-11-06 15:31 UTC, jrobichaud commented
Hi @rposborne.

I was wondering in which direction it was going finally:
- python-ipware to replace django-ipware
- django-ipware to use python-ipware

?

2023-11-09 14:43 UTC, rposborne commented
Closing as they are going to maintain the old one.

2023-11-09 14:43 UTC, closed without merging

2023-11-09 14:50 UTC, jrobichaud commented
As you seem to be a `django-ipware` and `python-ipware` aware, I have a question for you if you do not mind.

I was wondering if it would be useful to expose `django-ipware` configurations in `django-structlog` settings.

Some parameters have to be passed in the constructor and currently they are unavailable since django-structlog instantiates it directly. I am referring mainly about the proxy configuration.

What do you think?